const provincias = [
"Ciudad Autónoma de Buenos Aires",
"Mar del Plata, Provincia de Buenos Aires",
"Bariloche, Río Negro",
"Carlos Paz, Córdoba",
"Villa Gesell, Provincia de Buenos Aires",
"Termas de Río Hondo, Santiago del Estero",
"Partido de la Costa, Provincia de Buenos Aires",
"Salta, Provincia de Salta",
"Mendoza, Provincia de Mendoza",
"Iguazú, Misiones",
"Córdoba, Provincia de Córdoba",
"Pinamar, Provincia de Buenos Aires",
"Rosario, Santa Fe",
"Merlo, San Luis",
"Colón, Provincia de Entre Ríos",
"El Calafate, Santa Cruz",
"Puerto Madryn, Chubut",
"Tandil, Provincia de Buenos Aires",
"Ushuaia, Tierra del Fuego",
"Quebrada de Humahuaca, Jujuy",
"San Rafael, Mendoza",
"San Miguel de Tucumán",
"Federación, Entre Ríos",
"San Martín de los Andes, Neuquén",
"Villa General Belgrano, Córdoba",
]

module.exports = provincias;
