module.exports.names = [
    'Tierra de campeones',
    'El estadio',
    'La caldera',
    'Bernabeu',
    'Bombonera',
    'Monumental',
    'Mestalla',
    'Camp nou',
    'Potrero',
    'Qatar',
    'Megaestadio',
    'Supercancha',
    'VamoarribaUruguay',
    'Bosque',
    'Uno',
    'Santos',
    'Old Trafford',
    'Highbury',
    'Rio Grande',
    'Ensenada'
]